### ISSUE TITLE
Using distinct in a fields query returns wrong number of rows (duplicates)

### ISSUE THREAD

**Issue by alexbowers-tecmark** [UnionOfRAD/lithium#1175] opened 2015-03-20 10:17 UTC
When performing an $model::all(), if I pass fields as having distinct id, the rows get duplicated back.

The number of results if I perform the RAW sql query (as found in the queryString), is correct; but $result->data() gets the wrong number (double)

**Comment by davidpersson** [comment] 2015-03-20 12:25
To better understand the issue and in order to reproduce it, please provide a failing test case that demonstrates the problem. If you cannot provide a test case, the code fragment you're using as well as the query that gets generated (from the database log) is also OK.

**Comment by alexbowers-tecmark** [comment] 2015-03-20 13:23
SQL generated (obtained from queryString):

``` sql
SELECT distinct Attributes.id, `Attributes`.`name` FROM `attributes` AS `Attributes` WHERE `Attributes`.`deleted` = 0 ORDER BY `Attributes`.`order_num` ASC LIMIT 10;
```

Code:
``` php
$model = Attributes::all([
	'fields' => [
		'distinct Attributes.id',
		'name',
	],
	'conditions' => [
		'deleted' => 0,
	],
	'order' => [
		'order_num ASC'
	],
	'limit' => 10,
	'page' => 1,
]);
```

**Comment by alexbowers-tecmark** [comment] 2015-03-20 13:28
More details here: https://gist.github.com/alexbowers-tecmark/fb1e59ac3e6d8a0b1145

**Comment by alexbowers-tecmark** [comment] 2015-03-20 13:32
The issue appears to lie in the use of distinct Attributes.id, if I remove the distinct then it will not cause the bug. It gets the results only once.

**Comment by alexbowers-tecmark** [comment] 2015-03-20 13:36
Here is an example of the response when broken: https://gist.github.com/alexbowers-tecmark/e94a19868f9803dcb874

Here is an example of the response when correct: https://gist.github.com/alexbowers-tecmark/bf4102dc5cf55947d689

**Comment by davidpersson** [comment] 2015-03-20 18:54
What result would you expect? Can you describe your use case / what are you trying to achieve?

**Comment by alexbowers** [comment] 2015-03-20 22:00
I would expect the results to match the raw SQL. For me, the results should have been the same with or without the distinct keyword there (as SQL shows). But with the distinct keyword provided, the results got doubled up.

**Comment by davidpersson** [comment] 2015-03-21 00:56
Hi Alex, I'll see what I can do. Thanks for the information!

**Comment by alexbowers** [comment] 2015-03-21 04:26
Thanks :)

**Comment by davidpersson** [comment] 2015-03-30 13:00
I don't clearly understand what you actually expect the results to be. I assume you want all attributes unique names. Then you're query should be:

```php
Attributes::find('all', ['fields' => ['DISTINCT name']])
```

Or use GROUP BY, if you want more than just the name field returned.

```php
Attributes::find('all', ['group' => ['name']])
```

This is not a lithium bug, but a limitation in how (My)SQL works.

**Comment by alexbowers** [comment] 2015-03-30 13:53
@davidpersson It is a li3 bug, since  the generated SQL works fine (if ran in the mysql console), but the results from Li3 are not the same.

**Comment by davidpersson** [comment] 2015-03-30 15:56
@alexbowers You've posted the expected results under https://gist.github.com/alexbowers-tecmark/bf4102dc5cf55947d689 you've stated that the accompanying SQL query is `SELECT `Attributes`.`id`, `Attributes`.`name` FROM `attributes` AS `Attributes` WHERE `Attributes`.`deleted` = 0 ORDER BY `Attributes`.`order_num` ASC LIMIT 10;`. That doesn't even contain a DISTINCT.

The SQL query you've posted with the faulty results was `SELECT distinct Attributes.id, `Attributes`.`name` FROM `attributes` AS `Attributes` WHERE `Attributes`.`deleted` = 0 ORDER BY `Attributes`.`order_num` ASC LIMIT 10;`. That is just wrong SQL if what you want is unique attribute names. What you're asking the database for is unique combinations of id and name and as id is unique by definition you get all results back.

**Comment by alexbowers** [comment] 2015-03-30 16:00
Sorry, perhaps I wasn't clear.

The working SQL is the one that gets the correct response in Li3, the broken one is what doesn't work in Li3. Both of them work as expected in MySQL.

![image](https://cloud.githubusercontent.com/assets/842974/6900394/0eb8960a-d6fe-11e4-96a1-480c91227927.png)

![image](https://cloud.githubusercontent.com/assets/842974/6900403/1aa37d4a-d6fe-11e4-9d45-86ea14738ce0.png)

The issue also isn't with getting all results back, its that it gets the same results twice. In https://gist.github.com/alexbowers-tecmark/e94a19868f9803dcb874 the IDs are repeated, thus not distinct in the result.

**Comment by davidpersson** [comment] 2015-03-30 20:28
I cannot reproduce this issue. Although you've provided me with information I think I still don't quite understand where the problem is coming from nor what your original use case is.

Please **provide a failing test case to prove the bug** (through a pull request). I've committed a passing test case in 8a41127. This is a good point to start. Make sure to have a test connection defined in your testing app:
```php
Connections::add('test', array(
    'type' => 'database',
    'adapter' => 'MySql',
    'host' => 'localhost',
    'login' => 'root',
    'password' => '', 
    'database' => 'test',
    'encoding' => 'UTF-8'
));
```

Then run the test from the app via:
```
libraries/lithium/console/li3 test libraries/lithium/tests/integration/data/DatabaseTest.php 
```

I'm assuming that the `id` field in the attributes table is not a unique primary key and some sort of other "id"?

@alexbowers-tecmark Thanks for working with me on this!

**Comment by alexbowers** [comment] 2015-03-30 21:35
For the tests how should I go about populating and creating the database?

**Comment by davidpersson** [comment] 2015-03-30 22:27
You just need two things for that:

1. Create a database with the name `test`
2. Install the li3_fixtures plugin https://github.com/UnionOfRAD/li3_fixtures

Then in any test method of that case you'll have the empty galleries table available. Interface with it using the `Galleries` model. You have to create the records yourself (as I did in the test), you don't have to clean up as that's handled by li3_fixtures after each test run.

Give your test method a meaningful name. That's it!

Also see:
* http://li3.me/docs/lithium/test/Unit
* http://li3.me/docs/manual/quality-code/testing.md
* https://github.com/UnionOfRAD/lithium/blob/8a411272526b68d6cb59cd9eb4f943601876749a/tests/fixture/model/gallery/GalleriesFixture.php

**Comment by davidpersson** [comment] 2016-06-17 14:34
Feel free to reopen, but we'll need a failing test case.

**Closed by davidpersson** 2016-06-17 14:34 UTC
Labels: bug, works-for-me
