### ISSUE TITLE
Model::all(); not returning all documents from Mongodb

### ISSUE THREAD

**Issue by DMcP89** [UnionOfRAD/lithium#1165] opened 2015-02-14 18:22 UTC
I am going through lithum's quick start guide and I am having an issue displaying all the posts saved to my Mongo database.

I have setup my PostsController like so:

<?php

 namespace app\controllers;

 use app\models\Posts;

class PostsController extends \lithium\action\Controller {

    public function index(){
            $posts = Posts::all();
            return compact('posts');
    }

    public function add(){
            $post = Posts::create();
            $success = false;

            if($this->request->data && $post->save($this->request->data)){
                    $success = true;
            }
            return compact('post','success');
    }
}
?>
My add view is setup like this:

  <?=$this->form->create($post); ?>
    <?=$this->form->field('title');?>
    <?=$this->form->field('body', array('type' => 'textarea'));?>
    <?=$this->form->submit('save'); ?>
 <?=$this->form->end(); ?>

 <?php if ($success): ?>
    <p>Post Successfully Saved</p>
 <?php endif; ?>
And finally my index view is setup like this:

 <?php foreach ($posts as $post): ?>
     <article>
       <h1><?= $post->title ?></h1>
       <p><?= $post->body ?></p>
     </article>
 <?php endforeach; ?>
I have 4 test posts in my post collection as you can see from this output:

 db.posts.find();
 { "_id" : ObjectId("54dd379902a6ce7b088b4567"), "title" : "First    Post", "body" : "Test First Post" }
 { "_id" : ObjectId("54dd3b7e02a6ce7b088b4568"), "title" : "Test Post 2", "body" : "Test Post 2" }
 { "_id" : ObjectId("54dd3cfe02a6ceea0b8b4567"), "title" : "Test Post 3", "body" : "Test Post 3" }
 { "_id" : ObjectId("54dd3d1e02a6cee60b8b4567"), "title" : "Test Post 4", "body" : "Test Post 4" }
However when i view my index in a web browser it only displays the first 3 and not the final post. Also when a I add new post using the add view and then view my index again I will see everything but the post that was just added.

I am fairly new to Lithum, hence the quickstart guide, so I am not sure where I should start looking for my problem. It seems to me that the Posts::all() call is not returning everything it should

**Comment by davidpersson** [comment] 2015-02-15 12:18
Thanks for reporting the issue.

It's very likely that you're using a buggy mongo driver. Can you post the output of ` php -i | grep mongo`? Version 1.6.0 and 1.6.1 are affected. Also see #1160 and #1164.

**Comment by DMcP89** [comment] 2015-02-15 17:28
Here is the output from my machine:

Additional .ini files parsed => /etc/php5/cli/conf.d/mongo.ini,
mongo
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5


I am running on an ubuntu 12.04 machine, with mongo 2.6.7 and php 5.3.10.
Also what is interesting is when I run this test:

      $dbhost = "mongodb://localhost:27017";
      $dbConnection = new MongoClient($dbhost);
      $blog = $dbConnection->blog;
      $posts= blogf->posts;
      $findResults = $posts->find();
      echo var_dump(iterator_to_array($findResults));

I get all the documents back.

**Comment by davidpersson** [comment] 2015-02-15 17:46
Sorry I gave you the wrong command as the information is missing the mongo client version string. Please try this instead and paste the client version number in a comment below:
```
php --ri mongo
```

**Comment by DMcP89** [comment] 2015-02-15 17:52
Ahh i see, it would seem I am in fact using a buggy version

mongo

MongoDB Support => enabled
Version => 1.6.0
Streams Support => enabled
SSL Support => enabled
                   Supported Authentication Mechanisms                   
MONGODB-CR => enabled
SCRAM-SHA-1 => enabled
MONGODB-X509 => enabled
GSSAPI (Kerberos) => disabled
PLAIN => disabled

Directive => Local Value => Master Value
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.native_long => 1 => 1
mongo.long_as_object => 0 => 0
mongo.allow_empty_keys => 0 => 0
mongo.ping_interval => 5 => 5
mongo.is_master_interval => 15 => 15

**Comment by davidpersson** [comment] 2015-02-15 17:54
Closing, as this is an upstream bug and duplicate of #1160. @DMcP89 please upgrade to at least mongo driver version 1.6.2 or downgrade to 1.5.9 (if possible) both should work.

**Closed by davidpersson** 2015-02-15 17:54 UTC
Labels: bug, duplicate

**Comment by DMcP89** [comment] 2015-02-15 18:00
Worked like a charm thanks!
